#!/usr/bin/env bash
#a Bash script that configures a new Ubuntu machine
apt-get -y update
apt-get -y install nginx
ufw aloow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
