#!/usr/bin/env bash
# a Bash script that displays numbers from 1 to 100 and displays:
# FizzBuzz when the number is a multiple of 3 and 5
# Fizz when the number is multiple of 3
# Buzz when the number is a multiple of 5
i=1
while [ $i -le 100 ]; do
	f=$((i % 3))
	b=$((i % 5))
	if [ $f -eq 0 ] && [ $b -eq 0 ]; then
		echo "FizzBuzz"
	elif [ $b -eq 0 ]; then
		echo "Buzz"
	elif [ $f -eq 0 ]; then
		echo "Fizz"
	else
		echo "$i"
	fi
	((i++))
done
