#!/usr/bin/env bash
#Tells a story based on the contents of the "/etc/passwd/" file
while IFS=':' read -r uname passw uid gid information home shell; do
	echo "The user $uname is part of the $gid gang, "\
		"lives in $home and rides $shell."\
		"$uid's place is protected by the passcode $passw, "\
		"more info aboout the user here: $information"
	done
