#!/usr/bin/env bash
#A bash script that displays "Best School" 10 times but in the 9th time print "Hi"
count=0
while [ $count -lt 10 ]; do
	if [ $count -eq 8 ]; then
		echo "Hi"
	else
		echo "Best School"
	fi
done
