#!/usr/bin/env bash
# a Bash script that displays the time for 12 hours and 59 minutes
count=0
while [ $count -le 12 ]; do
	echo "Hour: $count"
	i=1
	while [ $i -lt 60 ]; do
		echo "$i"
		((i++))
	done
	((count++))
done
