#!/usr/bin/env bash
# A bash script that displays:
# - the content of the current directory
# - In a list format
# - Where only the part of the name after the first dash is displayed
for i in *; do
	cut -d'-' -f2 <<< "$i"
done
